### ISSUE TITLE
Queued location updates

### ISSUE THREAD

**Issue by bikeoid** [codeforgreenville/trolley-tracker-agent#11]
I left this analysis on another report - https://github.com/codeforgreenville/trolley-tracker/issues/101#issuecomment-151692486

**Comment by ajhodges** [comment]
Wow great sleuthing! I'll have to look more closely at what's happening in
the app. Seems like it could be as simple as decreasing the request
timeout.

**Comment by bikeoid** [comment]
I see the GPS update rate as small as 2 seconds on my tablet when it is running well.    A request timeout of 2 seconds could cause real updates to fail when the network is slow. Perhaps limit GPS update rate to 5 seconds and request timeout of something like 4 seconds.

**Comment by ajhodges** [comment]
I set the HTTP connection timeout and response timeout to both 3 seconds. I feel like this is long enough to account for slow connections/responses but short enough so that we never get the superspeed behavior. I've also increased the update interval to 4 seconds, though sometimes Android will give us updates faster than that.

I tested my code using the same methodology you used to discover this issue, by blocking a port in my router firewall. The timeout seems to be working great! Fingers crossed we never see our trolley speeding all over greenville again.
